version: "3.3"
services:
  app:
    build: .
    command: pm2-dev ./build/server.js
    environment:
      NODE_ENV: development
    ports:
    - "3000:3000"
    volumes:
    - .:/home/nodejs/app
    - ./node_modules:/home/nodejs/node_modules
