version: '3.3'
services:
  app:
    build: .
    command: npm run start
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/home/nodejs
      - ./node_modules:/home/nodejs/node_modules
