name: continuous integration
on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run lint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run test
        env:
          NATURAL_LANGUAGE: 'English'
          NATURAL_VOCABULARY: 'afinn'
          TWITTER_BEARER_TOKEN: 'FakeTokenABCD'
          TWITTER_RULES_URL: 'https://api.twitter.com/2/tweets/search/stream/rules'
          TWITTER_STREAM_URL: 'https://api.twitter.com/2/tweets/search/stream'
