name: continuous integration
on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: actions/setup-node@v1
        with:
          node: ${{ matix.node }}
      - run: npm install
      - run: npm run lint
